{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "outputs": [],
   "source": [
    "import math\n",
    "\n",
    "import os\n",
    "from scipy.stats import multivariate_normal\n",
    "import matplotlib.pyplot as plt\n",
    "from collections import defaultdict\n",
    "from time import sleep\n",
    "\n",
    "import dionysus as dn\n",
    "import numpy as np\n",
    "import multiprocessing, random\n",
    "from scipy.integrate import simps, dblquad\n",
    "\n",
    "from gtda.images import *\n",
    "from gtda.homology import CubicalPersistence\n",
    "import persistence_diagram, utils\n",
    "import tensorflow as tf"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [
    "param = {'cubical' : None,\n",
    "         'height': np.array([[0,1],[1,0]]),\n",
    "         'radial': np.array([[10,3],[20,6]]),\n",
    "         'erosion': [5],\n",
    "         'dilation': [10]\n",
    "         }\n",
    "\n",
    "train_images, train_labels, test_images, test_labels = utils.get_mnist_data(binirize=True)\n",
    "\n",
    "model = tf.keras.Sequential(\n",
    "    [tf.keras.layers.Flatten(input_shape=(28,28)),\n",
    "     tf.keras.layers.Dense(256,activation='relu'),\n",
    "     tf.keras.layers.Dense(126,activation='relu'),\n",
    "     tf.keras.layers.Dense(10),]\n",
    ")\n",
    "loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)\n",
    "\n",
    "model.compile(optimizer='adam',\n",
    "              loss=loss_fn,\n",
    "              metrics=['accuracy'])\n",
    "model.fit(train_images, train_labels, epochs=5)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [
    "probability_model = tf.keras.Sequential([\n",
    "  model,\n",
    "  tf.keras.layers.Softmax()\n",
    "])\n",
    "np.argmax(probability_model(test_images[0:1]))\n",
    "test_labels[0:1]"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [
    "model.evaluate(test_images,test_labels)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [
    "img  = train_images[0:1]\n",
    "\n",
    "er = DilationFiltration(n_iterations=10)\n",
    "er.fit_transform_plot(img)\n",
    "\n",
    "er = ErosionFiltration(n_iterations=None)\n",
    "er.fit_transform_plot(img)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [
    "a=np.array([1])\n",
    "print(type(int(a)))"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [
    "# Height filtration\n",
    "img  = train_images[1:5]\n",
    "\n",
    "num_of_vects = 6\n",
    "angles = np.linspace(0, math.pi/2, num_of_vects)\n",
    "dirs = [[round(math.cos(theta),2),round(math.sin(theta),2)] for theta in angles]\n",
    "dirs = np.array(dirs)\n",
    "print(dirs[5])\n",
    "h = HeightFiltration(direction=dirs[5])\n",
    "h.fit_transform_plot(img)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [
    "img  = train_images[1:2]\n",
    "rd = RadialFiltration(center=np.array([10,10]),radius=)\n",
    "rd.fit_transform_plot(img)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Computing persistence diagrams...\n",
      "Vectorizing persistence diagrams...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "Process Process-4:\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "Traceback (most recent call last):\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "Process Process-3:\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "Process Process-2:\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "Traceback (most recent call last):\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "Traceback (most recent call last):\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "  File \"/home/weaver/PycharmProjects/PerManifold/persistence_diagram.py\", line 158, in __compute_pds_chunk\n",
      "    filtered = er_fil.fit_transform(bin_image)\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/weaver/PycharmProjects/PerManifold/persistence_diagram.py\", line 158, in __compute_pds_chunk\n",
      "    filtered = er_fil.fit_transform(bin_image)\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/_docs.py\", line 106, in fit_transform_wrapper\n",
      "    return original_fit_transform(*args, **kwargs)\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "Process Process-5:\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "Traceback (most recent call last):\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/sklearn/base.py\", line 571, in fit_transform\n",
      "    return self.fit(X, **fit_params).transform(X)\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/weaver/PycharmProjects/PerManifold/persistence_diagram.py\", line 158, in __compute_pds_chunk\n",
      "    filtered = er_fil.fit_transform(bin_image)\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "Process Process-7:\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/_docs.py\", line 106, in fit_transform_wrapper\n",
      "    return original_fit_transform(*args, **kwargs)\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/_docs.py\", line 106, in fit_transform_wrapper\n",
      "    return original_fit_transform(*args, **kwargs)\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/sklearn/base.py\", line 571, in fit_transform\n",
      "    return self.fit(X, **fit_params).transform(X)\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "  File \"/home/weaver/PycharmProjects/PerManifold/persistence_diagram.py\", line 158, in __compute_pds_chunk\n",
      "    filtered = er_fil.fit_transform(bin_image)\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py\", line 708, in fit\n",
      "    self.get_params(), self._hyperparameters, exclude=['n_jobs'])\n",
      "Traceback (most recent call last):\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/_docs.py\", line 106, in fit_transform_wrapper\n",
      "    return original_fit_transform(*args, **kwargs)\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/validation.py\", line 188, in validate_params\n",
      "    return _validate_params(parameters_, references)\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py\", line 708, in fit\n",
      "    self.get_params(), self._hyperparameters, exclude=['n_jobs'])\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/sklearn/base.py\", line 571, in fit_transform\n",
      "    return self.fit(X, **fit_params).transform(X)\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py\", line 708, in fit\n",
      "    self.get_params(), self._hyperparameters, exclude=['n_jobs'])\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/sklearn/base.py\", line 571, in fit_transform\n",
      "    return self.fit(X, **fit_params).transform(X)\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/validation.py\", line 188, in validate_params\n",
      "    return _validate_params(parameters_, references)\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/sklearn/base.py\", line 571, in fit_transform\n",
      "    return self.fit(X, **fit_params).transform(X)\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/validation.py\", line 188, in validate_params\n",
      "    return _validate_params(parameters_, references)\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/_docs.py\", line 106, in fit_transform_wrapper\n",
      "    return original_fit_transform(*args, **kwargs)\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py\", line 708, in fit\n",
      "    self.get_params(), self._hyperparameters, exclude=['n_jobs'])\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/validation.py\", line 127, in _validate_params\n",
      "    ref_type = _validate_params_single(parameter, reference, name)\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/validation.py\", line 127, in _validate_params\n",
      "    ref_type = _validate_params_single(parameter, reference, name)\n",
      "  File \"/home/weaver/PycharmProjects/PerManifold/persistence_diagram.py\", line 158, in __compute_pds_chunk\n",
      "    filtered = er_fil.fit_transform(bin_image)\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/validation.py\", line 127, in _validate_params\n",
      "    ref_type = _validate_params_single(parameter, reference, name)\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/validation.py\", line 188, in validate_params\n",
      "    return _validate_params(parameters_, references)\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/validation.py\", line 95, in _validate_params_single\n",
      "    f\"Parameter `{name}` is of type {type(parameter)} while \"\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py\", line 708, in fit\n",
      "    self.get_params(), self._hyperparameters, exclude=['n_jobs'])\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/validation.py\", line 188, in validate_params\n",
      "    return _validate_params(parameters_, references)\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/validation.py\", line 127, in _validate_params\n",
      "    ref_type = _validate_params_single(parameter, reference, name)\n",
      "TypeError: Parameter `n_iterations` is of type <class 'numpy.int64'> while it should be of type (<class 'int'>, <class 'NoneType'>).\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/validation.py\", line 95, in _validate_params_single\n",
      "    f\"Parameter `{name}` is of type {type(parameter)} while \"\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/validation.py\", line 95, in _validate_params_single\n",
      "    f\"Parameter `{name}` is of type {type(parameter)} while \"\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/validation.py\", line 127, in _validate_params\n",
      "    ref_type = _validate_params_single(parameter, reference, name)\n",
      "TypeError: Parameter `n_iterations` is of type <class 'numpy.int64'> while it should be of type (<class 'int'>, <class 'NoneType'>).\n",
      "TypeError: Parameter `n_iterations` is of type <class 'numpy.int64'> while it should be of type (<class 'int'>, <class 'NoneType'>).\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/validation.py\", line 95, in _validate_params_single\n",
      "    f\"Parameter `{name}` is of type {type(parameter)} while \"\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/validation.py\", line 95, in _validate_params_single\n",
      "    f\"Parameter `{name}` is of type {type(parameter)} while \"\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "TypeError: Parameter `n_iterations` is of type <class 'numpy.int64'> while it should be of type (<class 'int'>, <class 'NoneType'>).\n",
      "Process Process-6:\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "Process Process-9:\n",
      "TypeError: Parameter `n_iterations` is of type <class 'numpy.int64'> while it should be of type (<class 'int'>, <class 'NoneType'>).\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/weaver/PycharmProjects/PerManifold/persistence_diagram.py\", line 158, in __compute_pds_chunk\n",
      "    filtered = er_fil.fit_transform(bin_image)\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "  File \"/home/weaver/PycharmProjects/PerManifold/persistence_diagram.py\", line 158, in __compute_pds_chunk\n",
      "    filtered = er_fil.fit_transform(bin_image)\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/_docs.py\", line 106, in fit_transform_wrapper\n",
      "    return original_fit_transform(*args, **kwargs)\n",
      "Process Process-10:\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/_docs.py\", line 106, in fit_transform_wrapper\n",
      "    return original_fit_transform(*args, **kwargs)\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/sklearn/base.py\", line 571, in fit_transform\n",
      "    return self.fit(X, **fit_params).transform(X)\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py\", line 708, in fit\n",
      "    self.get_params(), self._hyperparameters, exclude=['n_jobs'])\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/sklearn/base.py\", line 571, in fit_transform\n",
      "    return self.fit(X, **fit_params).transform(X)\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/validation.py\", line 188, in validate_params\n",
      "    return _validate_params(parameters_, references)\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/validation.py\", line 127, in _validate_params\n",
      "    ref_type = _validate_params_single(parameter, reference, name)\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py\", line 708, in fit\n",
      "    self.get_params(), self._hyperparameters, exclude=['n_jobs'])\n",
      "/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py:307: RuntimeWarning:\n",
      "\n",
      "invalid value encountered in multiply\n",
      "\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/validation.py\", line 95, in _validate_params_single\n",
      "    f\"Parameter `{name}` is of type {type(parameter)} while \"\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/validation.py\", line 188, in validate_params\n",
      "    return _validate_params(parameters_, references)\n",
      "TypeError: Parameter `n_iterations` is of type <class 'numpy.int64'> while it should be of type (<class 'int'>, <class 'NoneType'>).\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/weaver/PycharmProjects/PerManifold/persistence_diagram.py\", line 158, in __compute_pds_chunk\n",
      "    filtered = er_fil.fit_transform(bin_image)\n",
      "Process Process-11:\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/_docs.py\", line 106, in fit_transform_wrapper\n",
      "    return original_fit_transform(*args, **kwargs)\n",
      "Process Process-8:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/sklearn/base.py\", line 571, in fit_transform\n",
      "    return self.fit(X, **fit_params).transform(X)\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py\", line 708, in fit\n",
      "    self.get_params(), self._hyperparameters, exclude=['n_jobs'])\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/validation.py\", line 188, in validate_params\n",
      "    return _validate_params(parameters_, references)\n",
      "  File \"/home/weaver/PycharmProjects/PerManifold/persistence_diagram.py\", line 158, in __compute_pds_chunk\n",
      "    filtered = er_fil.fit_transform(bin_image)\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/_docs.py\", line 106, in fit_transform_wrapper\n",
      "    return original_fit_transform(*args, **kwargs)\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/sklearn/base.py\", line 571, in fit_transform\n",
      "    return self.fit(X, **fit_params).transform(X)\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py\", line 708, in fit\n",
      "    self.get_params(), self._hyperparameters, exclude=['n_jobs'])\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/validation.py\", line 188, in validate_params\n",
      "    return _validate_params(parameters_, references)\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/validation.py\", line 127, in _validate_params\n",
      "    ref_type = _validate_params_single(parameter, reference, name)\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/validation.py\", line 95, in _validate_params_single\n",
      "    f\"Parameter `{name}` is of type {type(parameter)} while \"\n",
      "TypeError: Parameter `n_iterations` is of type <class 'numpy.int64'> while it should be of type (<class 'int'>, <class 'NoneType'>).\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/validation.py\", line 127, in _validate_params\n",
      "    ref_type = _validate_params_single(parameter, reference, name)\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/validation.py\", line 127, in _validate_params\n",
      "    ref_type = _validate_params_single(parameter, reference, name)\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/validation.py\", line 95, in _validate_params_single\n",
      "    f\"Parameter `{name}` is of type {type(parameter)} while \"\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/validation.py\", line 95, in _validate_params_single\n",
      "    f\"Parameter `{name}` is of type {type(parameter)} while \"\n",
      "TypeError: Parameter `n_iterations` is of type <class 'numpy.int64'> while it should be of type (<class 'int'>, <class 'NoneType'>).\n",
      "TypeError: Parameter `n_iterations` is of type <class 'numpy.int64'> while it should be of type (<class 'int'>, <class 'NoneType'>).\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/multiprocessing/process.py\", line 297, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/multiprocessing/process.py\", line 99, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/home/weaver/PycharmProjects/PerManifold/persistence_diagram.py\", line 158, in __compute_pds_chunk\n",
      "    filtered = er_fil.fit_transform(bin_image)\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/_docs.py\", line 106, in fit_transform_wrapper\n",
      "    return original_fit_transform(*args, **kwargs)\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/sklearn/base.py\", line 571, in fit_transform\n",
      "    return self.fit(X, **fit_params).transform(X)\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/images/filtrations.py\", line 708, in fit\n",
      "    self.get_params(), self._hyperparameters, exclude=['n_jobs'])\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/validation.py\", line 188, in validate_params\n",
      "    return _validate_params(parameters_, references)\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/validation.py\", line 127, in _validate_params\n",
      "    ref_type = _validate_params_single(parameter, reference, name)\n",
      "  File \"/home/weaver/anaconda3/envs/tfgpu/lib/python3.7/site-packages/gtda/utils/validation.py\", line 95, in _validate_params_single\n",
      "    f\"Parameter `{name}` is of type {type(parameter)} while \"\n",
      "TypeError: Parameter `n_iterations` is of type <class 'numpy.int64'> while it should be of type (<class 'int'>, <class 'NoneType'>).\n"
     ]
    }
   ],
   "source": [
    "train_images, train_labels, test_images, test_labels = utils.get_mnist_data()\n",
    "train_images = train_images[0:10]\n",
    "\n",
    "## Set the params of the filtrations to extract\n",
    "\n",
    "# Height filtration\n",
    "num_of_vects = 6\n",
    "angles = np.linspace(0, math.pi/2, num_of_vects)\n",
    "dirs = [[round(math.cos(theta),2),round(math.sin(theta),2)] for theta in angles]\n",
    "dirs = np.array(dirs)\n",
    "\n",
    "# Radial filtration\n",
    "center = np.array([[10,10], [10,20], [20,10], [20,20]])\n",
    "radius = np.array([5, 10, 15])\n",
    "\n",
    "# Erosion filtration\n",
    "n_iter_er = np.array([1,2,3,50])\n",
    "\n",
    "# Dilation filtration\n",
    "n_iter_dil = np.array([1,3,5,10,50])\n",
    "\n",
    "params = {'cubical' : None,\n",
    "         'height': dirs,\n",
    "         'radial': {'center' : center,\n",
    "                    'radius' : radius\n",
    "                    },\n",
    "         'erosion': n_iter_er,\n",
    "         'dilation': n_iter_dil\n",
    "         }\n",
    "PD = persistence_diagram.PDiagram(train_images, params, man_dim=9)\n",
    "pds = PD.get_pds()\n",
    "vpds = PD.get_vectorized_pds()"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "outputs": [],
   "source": [
    "import pickle\n",
    "pickle.dump(pds, open('tmp.txt','wb'))\n"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "source": [
    "ld = pickle.load(open('data/diagrams/mnist_train/dgms.pkl','rb'))\n",
    "print(ld[0])\n"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   },
   "execution_count": 40,
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'cubical': None, 'height': array([[1.  , 0.  ],\n",
      "       [0.95, 0.31],\n",
      "       [0.81, 0.59],\n",
      "       [0.59, 0.81],\n",
      "       [0.31, 0.95],\n",
      "       [0.  , 1.  ]]), 'radial': {'center': array([[10, 10],\n",
      "       [10, 20],\n",
      "       [20, 10],\n",
      "       [20, 20]]), 'radius': array([ 5, 10, 15])}, 'erosion': array([ 1,  2,  3, 50]), 'dilation': array([ 1,  3,  5, 10, 50])}\n"
     ]
    }
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "outputs": [],
   "source": [
    "pps = pds.copy()\n",
    "pickle.dump(pps, open('tmp.txt','wb'))\n",
    "ld = pickle.load(open('tmp.txt','rb'))\n",
    "\n"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}